name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Add yarn
              run: npm i -g yarn
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build
            - name: start
              run: yarn start
