name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: BUILD
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build

    deploy:
        runs-on: self-hosted
        environment: BUILD
        needs: [build]
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: start
              run: npm run start
