name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: start
              run: npm run start
