name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: BUILD
            url: http://155.138.206.127:3000
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: echo "${{secrets.NEXT_PUBLIC_SUPABASE_URL}}"
            - name: Create env file
              run: |
                  echo "export BUILD_ENV=true" >> .env.local
                  echo "NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}" >> .env.local
                  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}" >> .env.local
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Build
              run: npm run build

    deploy:
        runs-on: self-hosted
        environment:
            name: DEPLOY
            url: http://155.138.206.127:3000/
        needs: [build]
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: start
              run: npm run start
